### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by mabrodeur** [flareman/homebridge-caddx-interlogix#3]
Hi,

Thanks for the plugin! I've been wanting to do this for a long time.

I'm having problems running it though. I added the plugin to my Homebridge instance and configured it through the UI.
It can connect to my NX595e successfully because at first I entered the wrong password and it showed me a "Cannot connect" message and now it doesn't.

But as soon as it launches I get that error and it crashes.

Do you have any idea how to fix this?

Thanks again !

```
TypeError: Cannot read property 'push' of undefined
at /usr/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:408:33
at Array.forEach (<anonymous>)
at /usr/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:405:22
at Array.forEach (<anonymous>)
at NX595ESecuritySystem.processZones (/usr/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:394:16)
at NX595ESecuritySystem.retrieveZones (/usr/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:380:10)
at processTicksAndRejections (internal/process/task_queues.js:94:5)
at NX595ESecuritySystem.login (/usr/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:85:7)
(node:114) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bank_state' of undefined
at NX595ESecuritySystem.getZoneBankState (/usr/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:571:30)
at /usr/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:180:41
at Array.forEach (<anonymous>)
at NX595EPlatform.discoverDevices (/usr/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:172:36)
at /usr/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:46:14
at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by flareman** [comment]
Seems like the plugin can't properly parse the zone details - it might have with the way the plugin processes areas and zone banks.

Does your installation have multiple areas? How many zones are there per area?

**Comment by mabrodeur** [comment]
I have a single area and 5 zones.
I managed to get a console.log of my area and zones.
Here is a JSON of my area/zones.

```
{
   "areas":[
      {
         "bank":0,
         "name":"Maison",
         "priority":6,
         "sequence":"53",
         "bank_state":[
            "0",
            "0",
            "1",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
         ],
         "status":"",
         "states":{
            
         }
      }
   ],
   "zones":[
      {
         "bank":7,
         "associatedArea":-1,
         "name":"Infra sous-sol",
         "priority":6,
         "sequence":0,
         "bank_state":[
            
         ],
         "status":"",
         "isBypassed":false,
         "autoBypass":false
      },
      {
         "bank":8,
         "associatedArea":-1,
         "name":"Porte avant",
         "priority":6,
         "sequence":0,
         "bank_state":[
            
         ],
         "status":"",
         "isBypassed":false,
         "autoBypass":false
      },
      {
         "bank":9,
         "associatedArea":-1,
         "name":"Porte patio",
         "priority":6,
         "sequence":0,
         "bank_state":[
            
         ],
         "status":"",
         "isBypassed":false,
         "autoBypass":false
      },
      {
         "bank":10,
         "associatedArea":-1,
         "name":"Infra salon",
         "priority":6,
         "sequence":0,
         "bank_state":[
            
         ],
         "status":"",
         "isBypassed":false,
         "autoBypass":false
      },
      {
         "bank":11,
         "associatedArea":-1,
         "name":"Fumee 2e etage",
         "priority":6,
         "sequence":0,
         "bank_state":[
            
         ],
         "status":"",
         "isBypassed":false,
         "autoBypass":false
      }
   ]
}
```

**Comment by mabrodeur** [comment]
I managed to prevent the crash by adding a condition to these two functions. It prevents the "undefined" problem.
With that I've been able to see all my sensors and the system in my Home app and everything. I can set arm/disarm on the system and see its state.
The problem I'm facing now is that the sensors states doesn't change. Even if I open my door for 2 minutes, the door sensor always stays off. Same for my motion sensor.

Do you have any idea? Hope my investigation helped a little bit.


   ```
 getZoneState(zone: number): boolean {
        if (typeof this.zones[zone] !== 'undefined' && typeof this.zones[zone].status !== 'undefined') {
            return !(this.zones[zone].status == ZoneState.Ready);
        }
        return false;
    }

    getZoneBankState(zone: number): string {
        if (typeof this.zones[zone] !== 'undefined' && typeof this.zones[zone].bank_state !== 'undefined') {
            return (this.zones[zone].bank_state.join(''));
        }

        return ("");
    }
```

**Comment by flareman** [comment]
You altered the zone state and bank state value getters to false and "", so it's natural that the plugin reports sensor state as not triggered :) Either way, seems like both the area state and status are not populated correctly, and the zones also are not parsed correctly.

To clarify, zones should start from bank zero, and yours starts from #7 (eight counts farther than they should), which likely has something to do with the associatedArea not being able to properly be set to 0 (which is your only assigned area).

May I ask, at which point of the code did you extract the JSON object? Zones and areas are properly populated after processAreas and processZones are both run. Also another question: the zones in the UltraSync web interface start at #0 as expected, correct?

**Comment by mabrodeur** [comment]
For some reason, I don't have zones from 1 to 7. 
Here you can see the zones I have when I log in to the NX-595E portal.
In the script, in the array the first 7 are named "%21" and not displayed in my interface.

For the JSON object, I got the output from the start of the processZones() function. Before the this.zones.forEach().

![image](https://user-images.githubusercontent.com/3265829/104960880-30e83e00-59a3-11eb-8320-7a8643e72180.png)
![image](https://user-images.githubusercontent.com/3265829/104961057-8fadb780-59a3-11eb-95fd-bc0ac4a9f7d7.png)

**Comment by flareman** [comment]
First off, great debugging, and kudos on the instant replies :)

On topic, this is interesting, and it explains a lot, actually. The plugin expects the zones to start from index zero; for some reason (probably due to the way your installer has set up your zones), your index starts at 7 (which you see as index+1, or 8, in your example). Odd zone assignment, though; I can't think of any valid reason for the installer to just skip over zones #0 to #6 and start assigning from #7 (maybe she wanted to "stock" those zones for future additions? Then again additional sensors could well be added after your initially installed five).

Two solutions for this issue:
Option #1 (the pedantic one): we continue to consider proper zone assignment as starting from 0, and you get your technician to reassign zones starting from the beginning. Not a good solution: it's narrow-sighted and it does not solve the issue, it just shifts it over to you, so I would go with...
Option #2 (the reasonable one): I will have to refactor the source code to account for "dead" zones like this. It will take some careful tinkering to get the plugin to ignore "dead" zones and only take notice of active ones, but it's fool- and futureproofing - not to mention good policy.

Due to a hectic work schedule this week, this may take some time, though :) I ask for your patience, as I will need your input to test this when I push an update.

**Comment by mabrodeur** [comment]
It is totally weird that the technician started at #7 for sure...
Option #2 would be the right was I guess.
I will try to do some parts on my side too and will be there for your tests when needed 👍🏻

**Comment by mabrodeur** [comment]
~~Further testings show that "dead" zones have their name set to "!". We might want to exclude these zones in a way.~~

EDIT: I see you are already ignoring them. So nevermind.

![image](https://user-images.githubusercontent.com/3265829/104962975-93dbd400-59a7-11eb-8ed0-d4bbcee344a9.png)

**Comment by mabrodeur** [comment]
Hello again.
As my zone number doesn't match with the index in the _zones_ array, I updated the functions to use the bank number instead of array index.
It works! If I open my door, the sensor triggers in homekit and I get the right state!

Might not be the cleanest way to do it, but here we go:

```
getZoneState(zone: number): boolean {
        let state = true;
        this.zones.forEach(z => {
            if (z.bank == zone) {
                state = !(z.status == ZoneState.Ready);
            }
        });
        return state;
    }

    getZoneBankState(zone: number): string {
        let bank_state = "";
        this.zones.forEach(z => {
            if (z.bank == zone) {
                bank_state = (z.bank_state.join(''));
            }
        });
        return bank_state;
    }
```

**Comment by flareman** [comment]
It does the trick in a pinch, but it does not account for e.g. missing zones in-between :) I'll get round to patching this, but in the meantime your solution works as a makeshift stopgap 👍🏻

**Comment by flareman** [comment]
Sorry for the delay; please try the latest 1.0.6 version. It should fix the issue, but as always I'm counting on you for debugging :)

Thanks, looking forward to your feedback.

**Comment by JoHoop** [comment]
Hey,
thanks so much for the plugin.
I'm running 1.0.6 but there's a TypeError when restarting my Homebridge.
I'll try debugging it. :)

```
TypeError: Cannot read property 'bank_state' of undefined
    at NX595ESecuritySystem.getZoneBankState (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:574:30)
    at /usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:180:41
    at Array.forEach (<anonymous>)
    at NX595EPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:172:36)
    at /usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:46:14
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by flareman** [comment]
> Hey,
> 
> thanks so much for the plugin.
> 
> I'm running 1.0.6 but there's a TypeError when restarting my Homebridge.
> 
> I'll try debugging it. :)
> 
> 
> 
> ```
> 
> TypeError: Cannot read property 'bank_state' of undefined
> 
>     at NX595ESecuritySystem.getZoneBankState (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:574:30)
> 
>     at /usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:180:41
> 
>     at Array.forEach (<anonymous>)
> 
>     at NX595EPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:172:36)
> 
>     at /usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:46:14
> 
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
> 
> ```

Thanks! Can you please grab a screenshot of your zone setup from the web interface (ideally from the names setting page) and post it here? Also, can you try the previous version and see if Homebridge does not crash? Some changes were made in 1.0.6 and they *might* have to do with this (then again, maybe not xD)

Thanks for the feedback.

**Comment by mabrodeur** [comment]
Hi! 
Fresh installed 1.0.6 on a new Homebridge dev setup I still have this error on boot: 

```
TypeError: Cannot read property 'push' of undefined
    at /usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:411:33
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:408:22
    at Array.forEach (<anonymous>)
    at NX595ESecuritySystem.processZones (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:397:16)
    at NX595ESecuritySystem.retrieveZones (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:383:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at NX595ESecuritySystem.login (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:85:7)
(node:4375) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bank_state' of undefined
    at NX595ESecuritySystem.getZoneBankState (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:574:30)
    at /usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:180:41
    at Array.forEach (<anonymous>)
    at NX595EPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:172:36)
    at /usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:46:14
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4375) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4375) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Do you want me to provide anything? I can't really debug for a few days

**Comment by flareman** [comment]
So it's not fixed yet. Fair enough, sit tight for now; a fellow user also had an issue and they might be connected. I'll have to take a better look at the code and determine the actual cause of the problem.

**Comment by JoHoop** [comment]
> Thanks! Can you please grab a screenshot of your zone setup from the web interface (ideally from the names setting page) and post it here? Also, can you try the previous version and see if Homebridge does not crash? Some changes were made in 1.0.6 and they _might_ have to do with this (then again, maybe not xD)
> 
> Thanks for the feedback.

Really appreciate your help!!
This is my zoneNames array.

```
var areaNames = new Array(
  "Home",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21"
);
var zoneNames = new Array(
  "Bewegung%20Flur",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "Haust%C3%BCr",
  "K%C3%BCche",
  "Esszimmer",
  "T%C3%BCr%20Esszimmer",
  "Wohnen%201",
  "Wohnen%202",
  "Wohnen%203",
  "Hauswirtschaftsraum",
  "G%C3%A4ste%2DWC",
  "Kinderzimmer%20L",
  "Kinderzimmer%20J",
  "Abstellraum",
  "Bad",
  "Arbeitszimmer",
  "Schlafzimmer",
  "Bett%20links",
  "Bett%20rechts",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "Rauch%20Flur",
  "Rauch%20Flur%20oben",
  "Rauch%20Schlafzimmer",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21",
  "%21"
);
```

**Comment by flareman** [comment]
> > Thanks! Can you please grab a screenshot of your zone setup from the web interface (ideally from the names setting page) and post it here? Also, can you try the previous version and see if Homebridge does not crash? Some changes were made in 1.0.6 and they _might_ have to do with this (then again, maybe not xD)
> 
> > 
> 
> > Thanks for the feedback.
> 
> 
> 
> Really appreciate your help!!
> 
> This is my zoneNames array.
> 
> 
> 
> <img width="654" alt="zoneNames" src="https://user-images.githubusercontent.com/67421398/106192394-6adbf000-61ac-11eb-9ad7-b8aab63060f0.png">
> 
> 

Thanks; it seems that your setup has the same "problem" reported above in this thread: it skips zones from #1 till #7, and then again from #25 till #31. Debugging is difficult because I can't change the setup in my own installation and I have to rely on commits and updates from you folks to sort this out but with some patience I believe we'll get it right.

Please wait on an update on my side; you can give me some feedback after that and we can take it from there.

**Comment by JoHoop** [comment]
Thanks so much!
Anything we can do to help? :)

**Comment by JoHoop** [comment]
I‘ve opened a PR #4 

> I'd suggest to insert each zone at their bank number, instead of pushing it to the zones array.
> 
> This fixes `TypeError: Cannot read property 'bank_state' of undefined` at line 580.
> Now you can retrieve zones without crashing.
> 
> However, there's still an error when processing the retrieved zones.
> `this._zvbank[zone.bank]` at line 411 is undefined if it's a dead zone.

This is the same error @mabrodeur is having.
If you could explain what the zvbank is supposed to do then maybe I‘d able to fix it. @flareman :)

**Comment by flareman** [comment]
@JoHoop Terribly sorry for the absence, it's been a very hectic period with day work :(

Okay, let me try to explain how the system stores zones information: the zonesBank property stores the entire zones bank for the whole system. Every one of the 17 entries in the array is essentially the zone property values for all areas of the entire security system in bitmask format and every area theoretically has a maximum of 16 possible zones. The processZones function determines two values: mask and index. Index is the area to which the zone is assigned, and is calculated as the rounded down result of the division of the zone bank by 16, and mask is the bitmask position for the particular boolean zone property we want to access, and is calculated as a right shift of the value one by the modulus of the same division. That practically means that zone banks start counting from zero, then go up to 15, and zone bank 16 is the first zone for the second area, and so on. Therefore, if I want to access the flag at the fourth position for the third zone of the second area, I have to get the fourth zonesBank array element, then get its second element, and then get its third bit flag value and convert it to boolean. In the example above, said zone would have a zone bank of (1*16)+2)-1, which calculates down to 17. _zvbank is practically a parsed array of all bit flag values in ready to access format, where every element is a zone array and each such array has this particular zone's flags as elements. In this way, the system can easily access the flags it needs to calculate the ready/not ready status of a zone for arming/disarming, without having to calculate the exact bit every single time.

[edit]
In your pull req changes, line 411 crashes because the system skips on parsing zones that have "" or "!" or "%21" as their zone name, because it means that the zone is not set up. What you propose would require a minor rework, the zones array should be initialized with the maximum possible size (different network interface models and firmware versions support different amounts of zones), but it is possible.
[/edit]

Hope I was clear, it was a headache to understand in the first place xD. We still don't know what most of the zone flags do, other than flag 4 which is the bypassed state, and flag 9 which is the autobypass flag for interior radars (they bypass on stay arm). Alas, the woes of blind reverse engineering 🤷

If you have the inclination and the time to work on that pull request more, you would help a lot with the debugging. No obligations though, apparently :)

Out of curiosity, how many areas do you have in your setup?

**Comment by JoHoop** [comment]
Thanks so much for the explanation. Really appreciate it. :)

> Out of curiosity, how many areas do you have in your setup?

I have just one area.

I'll try my best to fix it!

**Comment by flareman** [comment]
> Thanks so much for the explanation. Really appreciate it. :)
> 
> > Out of curiosity, how many areas do you have in your setup?
> 
> I have just one area.
> 
> I'll try my best to fix it!

Your setup seems to have three sets of 16 zones each, so either your version of the interface supports more than 16 zones at once, or you have three areas and you just arm them all at the same time via the keypad. We should somehow check whether you can arm one of three areas independently of the others; this opens up discussion on adding separate arming accessories for each area, in addition to a central one for arming everything at once.

**Comment by JoHoop** [comment]
I'm not quite sure I understand.
I have 48 zone banks in total but not all of them are set up. Therefore I'd need to process 3 areas?
But my `areaNames` array from the web interface only has one element: `"Home"`.
Yet my `zonesBank` array looks like this:
```
[
  [ 8192, 0, 0, 0 ], [ 0, 0, 0, 0 ],
  [ 0, 0, 0, 0 ],    [ 0, 0, 0, 0 ],
  [ 0, 0, 0, 0 ],    [ 0, 0, 0, 0 ],
  [ 0, 0, 0, 0 ],    [ 0, 0, 0, 0 ],
  [ 0, 0, 0, 0 ],    [ 0, 0, 0, 0 ],
  [ 0, 0, 0, 0 ],    [ 0, 0, 0, 0 ],
  [ 0, 0, 0, 0 ],    [ 0, 0, 0, 0 ]
]
```

**Comment by flareman** [comment]
The most possible scenario is that your system supports more than 16 zones per area.

Can you do something for me? Log into the panel's web interface and check the sources for the status.js script. There should be a buildArea function, an updateArea function and an updateZone function. Could you copy these and paste those here for me? Also, what is the value for the version and release properties of the securitySystem instance of the plugin in your case?

I want to check what version your firmware is, as well as how your version of the interface parses zones and areas. Maybe your 595 is a different build from mine and processes this info in a different fashion.

**Comment by JoHoop** [comment]
Sure!

> Also, what is the value for the version and release properties of the securitySystem instance of the plugin in your case?

How can I check? :D

```javascript
function buildArea(area)
{
  var mask = 255;
  var start = 0;
  if (area != 0) {
    mask = (0x01 << ((area - 1) % 8));
    start = (Math.floor((area - 1) / 8));
  }
  var div1 = document.createElement("div");
  div1.id = ("a" + area);
  div1.className = 'box';
  div1.innerHTML =
    '<h1></h1> \
        <h2></h2> \
        <button type="button" class="ba"><div class="bi"></div>'+areaLanguage[0]+'</button> \
        <button type="button" class="bs"><div class="bi"></div>'+areaLanguage[1]+'</button> \
        <button type="button" class="bo"><div class="bi"></div>'+areaLanguage[2]+'</button> \
        <button type="button" class="bc"><div class="bi"></div>'+areaLanguage[3]+'</button>';

  if (area == 0)
    div1.getElementsByTagName('h1')[0].innerHTML = miscLabels[0];
  else
    div1.getElementsByTagName('h1')[0].innerHTML = areaNames[area - 1];

  var cmd = "newAJAXCommand('/user/keyfunction.cgi', cgiResponse, false," + "'comm=80&data0=2&data2=17&data1=" + mask + "')";
  div1.getElementsByTagName('button')[0].setAttribute('onclick', cmd);
  var cmd = "newAJAXCommand('/user/keyfunction.cgi', cgiResponse, false," + "'comm=80&data0=2&data2=18&data1=" + mask + "')";
  div1.getElementsByTagName('button')[1].setAttribute('onclick', cmd);
  var cmd = "newAJAXCommand('/user/keyfunction.cgi', cgiResponse, false," + "'comm=80&data0=2&data2=16&data1=" + mask + "')";
  div1.getElementsByTagName('button')[2].setAttribute('onclick', cmd);
  var cmd = "newAJAXCommand('/user/keyfunction.cgi', cgiResponse, false," + "'comm=80&data0=2&data2=1&data1=" + mask + "')";
  div1.getElementsByTagName('button')[3].setAttribute('onclick', cmd);
  document.getElementById('at').appendChild(div1);

  areaDisplay.push(0);
  if (area == 0)
    updateSystemDisplay(true);
  else
    updateArea(area);
}
```

```javascript
function updateArea(area)
{
  try {
    var stat = document.getElementById('a' + area); // gets the div
    if (stat == null)
      return;
    var buttons = stat.getElementsByTagName('button');
    var i = area - 1;
    var areaString = "";
    var bgtype = 'bg-grn';
    var byteindex = (Math.floor(i / 8) * 17);
    var mask = (0x01 << (i % 8));
    var starm = parseInt(areaStatus[byteindex], 10);
    var stpartial = parseInt(areaStatus[byteindex + 1], 10);
    var stchime = parseInt(areaStatus[byteindex + 15], 10);
    var stexit1 = parseInt(areaStatus[byteindex + 7], 10);
    var stexit2 = parseInt(areaStatus[byteindex + 8], 10);
    var cmd;


    if ((parseInt(areaStatus[byteindex + 3], 10) & mask) != 0 ||
      (parseInt(areaStatus[byteindex + 4], 10) & mask) != 0 ||
      (parseInt(areaStatus[byteindex + 5], 10) & mask) != 0 ||
      (parseInt(areaStatus[byteindex + 6], 10) & mask) != 0) {
      allpriority = 1;
      bgtype = "bg-red";
    } else
    if ((parseInt(areaStatus[byteindex + 11], 10) & mask) != 0 ||
      (parseInt(areaStatus[byteindex + 12], 10) & mask) != 0 ||
      (parseInt(areaStatus[byteindex + 13], 10) & mask) != 0 ||
      (parseInt(areaStatus[byteindex + 14], 10) & mask) != 0 ||
      (sysStatus != null && sysStatus.length > 1)) {
      if (allpriority != 1)
        allpriority = 2;
      bgtype = "bg-blue";
    } else
    if ((parseInt(areaStatus[byteindex + 10]) & mask) != 0 || (stpartial & mask) != 0) {
      if (allpriority > 3)
        allpriority = 3;

      bgtype = "bg-yel";
    } else
    if ((starm & mask) != 0) {
      if (allpriority > 4)
        allpriority = 4;

      bgtype = "bg-red";
    } else
    if ((parseInt(areaStatus[byteindex + 2], 10) & mask) == 0) {
      if (allpriority > 5)
        allpriority = 5;

      bgtype = "bg-gry";
    }


    while (areaString == "") {
      if (areaDisplay[i] >= areaStates.length) {
        var maxCount;

        if (areaCount > 1)
          maxCount = (areaStates.length);
        else
          maxCount = (areaStates.length + sysStatus.length);

        if (areaDisplay[i] >= maxCount) {
          if (((stexit1 & mask) != 0) || ((stexit2 & mask) != 0))
            areaDisplay[i] = 3;
          else
            areaDisplay[i] = 0;
        } else {
          areaString = sysStatus[areaDisplay[i] - areaStates.length];
          if (areaString == "No System Faults") {
            areaString = systemStates[0];
          }
          areaDisplay[i]++;
        }
      } else {
        var st = parseInt(areaStatus[areaDisplay[i] + byteindex], 10);
 
        if ((st & mask) != 0) {
          if ((areaDisplay[i] != 2) || ((starm & mask) == 0 && (stpartial & mask) == 0)) {
            areaString = areaStates[areaDisplay[i]];
          }
          if (areaDisplay[i] == 7)
            areaDisplay[i]++;
        } else if (areaDisplay[i] == 2 && (starm & mask) == 0 && (stpartial & mask) == 0) {
          areaString = areaLanguage[4];
        }

        areaDisplay[i]++;
      }
    }

    if (stat.getElementsByTagName('h2')[0].innerHTML != areaString) {
      stat.getElementsByTagName('h2')[0].innerHTML = areaString;
      stat.firstChild.className = bgtype; // for h1 element
    } else
    if (stat.firstChild.className != bgtype) {
      stat.firstChild.className = bgtype;
    }

    if ((starm & mask) != 0) {
      buttons[0].className = 'ba bg-red';
      buttons[1].className = 'bs bg-gry';
      allStay = false;
    } else if ((stpartial & mask) != 0) {
      buttons[0].className = 'ba bg-gry';
      buttons[1].className = 'bs bg-yel';
      allAway = false;
    } else {
      buttons[0].className = 'ba bg-gry';
      buttons[1].className = 'bs bg-gry';
      allStay = false;
      allAway = false;

    }

    if ((stchime & mask) != 0) {
      if (buttons[3].className != 'bc bg-blu') {
        buttons[3].className = 'bc bg-blu';
        cmd = "newAJAXCommand('/user/keyfunction.cgi', cgiResponse, false," + "'comm=80&data0=2&data2=1&data1=" + mask + "')";
        buttons[3].setAttribute('onclick', cmd);
      }
    } else {
      allChime = false;
      if (buttons[3].className != 'bc bg-gry') {
        buttons[3].className = 'bc bg-gry';
        cmd = "newAJAXCommand('/user/keyfunction.cgi', cgiResponse, false," + "'comm=80&data0=2&data2=1&data1=" + mask + "')";
        buttons[3].setAttribute('onclick', cmd);
      }
    }
  } catch (err) {
    alert("" + err);
  }
}
```

```javascript
function updateZone(zone)
{
  if (zone == null)
    return;

  try {
    var stat = document.getElementById('z' + zone); // gets the div
    var buttons = stat.getElementsByTagName('button');

    var i = zone - 1;
    var zoneString = "";
    var bgtype = 'bg-grn';
    var byteindex = Math.floor(i / 16);
    var mask = (0x01 << (i % 16));
    var st;
    var cmd;

    if ((parseInt(zoneStatus[5][byteindex], 10) & mask) != 0)
      bgtype = "bg-red";
    else
    if ((parseInt(zoneStatus[1][byteindex], 10) & mask) != 0 ||
      (parseInt(zoneStatus[2][byteindex], 10) & mask) != 0 ||
      (parseInt(zoneStatus[6][byteindex], 10) & mask) != 0 ||
      (parseInt(zoneStatus[7][byteindex], 10) & mask) != 0)
      bgtype = "bg-blue";
    else
    if ((parseInt(zoneStatus[3][byteindex], 10) & mask) != 0 || (parseInt(zoneStatus[4][byteindex], 10) & mask) != 0)
      bgtype = "bg-yel";
    else
    if ((parseInt(zoneStatus[0][byteindex], 10) & mask) != 0)
      bgtype = "bg-gry";

    while (zoneString == "") {
      if (zoneDisplay[i] >= zoneStates.length)
        zoneDisplay[i] = 0;

      st = parseInt(zoneStatus[zoneDisplay[i]][byteindex], 10);

      if ((st & mask) != 0) {
        zoneString = zoneStates[zoneDisplay[i]];
      } else
      if (zoneDisplay[i] == 0) {
        zoneString = zoneLanguage[1];
      }
      zoneDisplay[i]++;
    }

    if (stat.getElementsByTagName('h2')[0].innerHTML != zoneString) {
      stat.getElementsByTagName('h2')[0].innerHTML = zoneString;
      stat.firstChild.className = bgtype; // for h1 element
    } else
    if (stat.firstChild.className != bgtype) {
      stat.firstChild.className = bgtype;
    }
    /*
    st = parseInt(zoneStatus[9][byteindex],10);
    if((st & mask)!= 0)
    {
        if (buttons[1].className != 'bc bg-blu')
        {
            buttons[1].className = 'bc bg-blu';
            cmd = "newAJAXCommand('/user/zonefunction.cgi', zoneCGIresponse, false,"+  "'comm=82&data0="  + (zone-1) +"')";
            buttons[1].setAttribute('onclick', cmd);
        }
    }
    else
    {
        if (buttons[1].className != 'bc bg-gry')
        {
            buttons[1].className = 'bc bg-gry';
            cmd = "newAJAXCommand('/user/zonefunction.cgi', zoneCGIresponse, false,"+  "'comm=82&data0="  + (zone-1) +"')";
            buttons[1].setAttribute('onclick', cmd);
        }
    }
    */
    st = parseInt(zoneStatus[3][byteindex], 10);
    if ((st & mask) != 0) {
      if (buttons[0].className != 'bc bg-yel') {
        buttons[0].className = 'bb bg-yel';
        cmd = "newAJAXCommand('/user/zonefunction.cgi', zoneCGIresponse, false," + "'comm=82&data0=" + (zone - 1) + "')";
        buttons[0].setAttribute('onclick', cmd);
      }
    } else {
      if (buttons[0].className != 'bc bg-gry') {
        buttons[0].className = 'bb bg-gry';
        cmd = "newAJAXCommand('/user/zonefunction.cgi', zoneCGIresponse, false," + "'comm=82&data0=" + (zone - 1) + "')";
        buttons[0].setAttribute('onclick', cmd);
      }
    }
  } catch (err) {
    alert("" + err);
  }
}
```

**Comment by flareman** [comment]
Okay, we have the same web interface code.


```
    var i = zone - 1;
    var byteindex = Math.floor(i / 16);
    var mask = (0x01 << (i % 16));

    [...]

    if ((parseInt(zoneStatus[5][byteindex], 10) & mask) != 0)

```

This is the code that dictates the logic behind zone parsing; zoneStatus is the entire array of statuses, with one element per flag for all zones and areas, byteindex is the "area" (let's call it zone bank) where the specific zone is assigned, and mask is the actual bit flag mask for this particular zone. The parseInt line checks for the sixth flag: it grabs the sixth element of zoneStatus (which has the sixth flag values for the entire system), and then checks the bit mask for the particular zone being parsed against the byte index.

This means that the system indeed supports up to 8 areas, and that every area supports up to (theoretically) 16 zones. I would guess that - depending on the installer specifics - more than 16 zones can be assigned to an area, but the web interface separates them into multiple "banks", without it affecting the actual function of the system. Does your keypad display up to 48 zone LEDs?

**Comment by flareman** [comment]
Given that we have the ball rolling on this issue, I just pushed an update where I tried to fix this problem using your suggestion. Give it a whirl and let me know if it works properly now :)

**Comment by JoHoop** [comment]
`this.zones[zone]` in line 575 is still undefined, but my PR #4 will fix that! :D

**Comment by flareman** [comment]
> `this.zones[zone]` in line 575 is still undefined, but my PR #4 will fix that! :D

The pull request was merged, and I fixed the initial zones population as well. Let's try this again :)

**Comment by JoHoop** [comment]
We're close! :D
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bank' of undefined
    at /usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:173:51
    at Array.forEach (<anonymous>)
    at NX595EPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:172:36)
    at /usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platform.ts:46:14
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by flareman** [comment]
Zone handling was assuming that all zones are valid; changed the zone parsing to ignore undefined entries in platform.ts in v1.0.9.

I hope this should do it :)

**Comment by JoHoop** [comment]
Everything is working!! This is amazing.
Thank you so much.

**Comment by JoHoop** [comment]
Only sending bypass commands to contact sensors does not yet work.

```
TypeError: Cannot read property 'bank' of undefined
    at NX595ESecuritySystem.sendZoneCommand (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:147:52)
```

**Comment by flareman** [comment]
Yes, the zone command function did not check for undefined entries; it should be fixed in 1.0.10 which is already live:)

edit: Still not working, wait for a newer update.
edit: Please try version 1.0.11 :)

**Comment by JoHoop** [comment]
When clicking the Bypass button Homebridge crashes. :D
```
TypeError: Cannot read property 'states' of undefined
    at NX595ESecuritySystem.getAreaArmStatus (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:592:30)
    at NX595EPlatformContactSensorAccessory.setBypassState (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platformAccessory.ts:127:50)
...
```

**Comment by flareman** [comment]
> When clicking the Bypass button Homebridge crashes. :D
> 
> ```
> TypeError: Cannot read property 'states' of undefined
>     at NX595ESecuritySystem.getAreaArmStatus (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:592:30)
>     at NX595EPlatformContactSensorAccessory.setBypassState (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/platformAccessory.ts:127:50)
> ...
> ```

This is possibly an entirely different issue; can you check the area argument being passed into the function, as well as the areas property values?

**Comment by JoHoop** [comment]
Sure!

The accessory is associated to `area` 1.
But I only have one area, so `this.areas[area]` is undefined.
```javascript
this.areas = [
  {
    bank: 0,
    name: "Home",
    priority: 2,
    sequence: 106,
    bank_state: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    status: "Ready",
    states: {
      armed: false,
      partial: false,
      chime: false,
      exit1: false,
      exit2: false,
    },
  },
];
```

**Comment by flareman** [comment]
This is because of the initial plugin logic, which assumes that each area has 16 zones at most. The plugin checks the armed status of the mother area before issuing a bypass command, because of the way the system works (bypass changes are not allowed if the alarm is armed).

I published 1.0.12 which disables the check entirely; we still need a way to determine which zones are assigned to each area. Please check the latest version and let me know if it works.

**Comment by JoHoop** [comment]
> Please check the latest version and let me know if it works.

Yes, it does! Thank you so much.
